version: "3.7"

services: 
  rentx_postgres:
    image: postgres
    container_name: rentx_postgres
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx 
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: rentx
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - rentx_postgres
    depends_on: 
      - rentx_postgres


volumes:
  pgdata:
    driver: local 
